### ISSUE TITLE
How to use it locally without npm package publish

### ISSUE THREAD

**Issue by Vishwas-75** [michaldudak/plain-design-system#1]
Hey @michaldudak ,

I need to test this package local i followed the below steps:

Step 1: Build the package with script `yarn build`
Setp 2: Run the `yarn link` to make it available locally
Step 3: Run the `yarn link rebased-design-system` in consumer project to access the components 

Expected Result: I can import components and use it.
Actual Result:  Getting error `Cannot find module 'rebased-design-system'`

Could you please help do i need to any extra configuration to make it work??

**Comment by michaldudak** [comment]
It should be possible now. The package.json wasn't configured properly. I tested it with another vite app using `pnpm link`. Let me know if it works.
